### ISSUE TITLE
RequestPermissionsAsync never returns when permission is requested

### ISSUE THREAD

**Issue by Devvox93** [jamesmontemagno/PermissionsPlugin#94] opened 2018-04-23 09:39 UTC
https://github.com/jamesmontemagno/PermissionsPlugin/blob/22a4851cdc066b7e753e21bbeaf0735264d231a7/src/Plugin.Permissions/Permissions.android.cs#L191

I get an exception on this line if a permission needs to be requested.
The specific exception is "Task got cancelled".

After either denying or allowing the permission prompt, further code after the call to this method is not executed and therefore I cannot check the result of the requested permission.

As workaround I now directly call ActivityCompat.RequestPermissions with a fixed string "android.permission.CAMERA" as that is the one I need at the moment.
However I would like to use this plugin if it works as intended.

UPDATE: This issue is very similar to what's described in #85 

Another UPDATE: Turns out I had the OnRequestPermissionsResult in the wrong file.
I now manually re-check the permissions in this method after they are requested.
It would still be nice if the method would actually return its return type
`Task<Dictionary<Permission, PermissionStatus>>`
Therefore I leave this issue open.

**Comment by rizamarhaban** [comment] 2018-04-24 06:49
try my work around here: https://github.com/jamesmontemagno/PermissionsPlugin/issues/93#issuecomment-383477835

**Comment by Devvox93** [comment] 2018-04-24 09:39
Thanks @rizamarhaban. I have a different workaround, like described in the 2nd update. It works, but the possibility of crashes seems enough reason to let the author look into this in more detail and come with a solid solution.

**Comment by jamesmontemagno** [comment] 2018-04-24 16:14
Closing as it was missconfigured

**Closed by jamesmontemagno** 2018-04-24 16:14 UTC

**Comment by Devvox93** [comment] 2018-04-24 16:49
@jamesmontemagno It was, but the fact still is that that method does not return its return type in all cases (like when permissions are requested).
Therefore the task stays open and on moving to another view/fragment the task is cancelled by a dispose, which causes the crash.

Saying "misconfigured" is the easy fix. Oh wait, it isn't a fix...
Anyway, it's your library bro. No hard feelings as I've worked around this bug.

**Comment by jamesmontemagno** [comment] 2018-04-24 17:02
If you create a small reproduction of the issue that would help. I have not had any issues like this at all in my apps, so actually seeing the issue is important to fix it.

**Comment by Devvox93** [comment] 2018-04-24 17:14
You're right. I'll post that tomorrow.

**Comment by jamesmontemagno** [comment] 2018-04-24 17:15
Can you post that with a new clean issue as well :)

**Comment by Devvox93** [comment] 2018-04-26 11:44
@jamesmontemagno A day delay, but the new issue is #95
