### ISSUE TITLE
iOS 11 - Add new permission NSLocationAlwaysAndWhenInUseUsageDescription

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/PermissionsPlugin#60] opened 2017-09-21 16:03 UTC
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:
Device Tested On:
Simulator Tested On:
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

**Comment by Moltroon** [comment] 2017-09-22 09:40
Hello,
When I used this plugin on iOS 11 to activate Location permission, the "WhenInUseUsagedescription" do not appear and infinite loop start. For they other permissions, this plugin work fine.

# Bug Information
**Version number of plugin:** 2.0.1
**Device tested on:** iPhone 5S with iOS 11
**Simulator tested on:** iPhone 8 iOS 11
**Version of VS:** 7.1.5 (build 2)
**Version of Xamarin:** Xamarin.Forms 2.3.4.270 (latest stable)
**Versions of other things you are using:** 
- Newtonsoft.Json (10.0.3)
- PCLStorage (1.0.2)
- sqlite-net-pcl (1.4.118)
- SQLitePCLRaw.bundle_green (1.1.8)
- SQLitePCLRaw.core (1.1.8)
- Xam.Plugin.DeviceInfo (3.0.1)
- Xam.Plugin.Geolocator (4.0.1)
- Xam.Plugin.Media (3.0.1)
- Xamarin.Forms.Maps (2.3.4.270) (PS : WhenInUseUsageDescription work fine with her)

# Steps to reproduce the Behavior
Integrate my code

# Expected Behavior
A message appear to allow Location authorization

# Actual Behavior
No message and infinite loop

# Code Snippet
`
var locationStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Location);
if (locationStatus != PermissionStatus.Granted)
{
var results = await CrossPermissions.Current.RequestPermissionsAsync(new[] { Permission.Location });
locationStatus = results[Permission.Location];
}
`

**Comment by jamesmontemagno** [comment] 2017-09-22 17:14
You need to add this new permission to your info plist and handle it yourself manually as I do not compile against iOS 11 yet.

**Comment by Moltroon** [comment] 2017-09-25 08:40
I have add this new permission and it works. Visual Studio for Mac not integrate this new permission today.

**Comment by prashantvc** [comment] 2017-10-10 05:55
I am marking this issue closed as per the comment above
@Moltroon please reopen the issue if you continue to have a problem

**Closed by prashantvc** 2017-10-10 05:55 UTC
Labels: triaged

**Comment by PureWeen** [comment] 2017-10-16 17:56
Should 2.1.0 handle "NSLocationAlwaysAndWhenInUseUsageDescription" or will "NSLocationAlwaysAndWhenInUseUsageDescription" just be dealt with in a future milestone?  I'm guessing the latter but just wanted to clarify since this was added to milestone 2.1.0 but still doesn't seem to be dealt with.

**Comment by jamesmontemagno** [comment] 2017-10-16 22:09
Yes, but you should be smart on how and when you ask. It isn't bullet proof. Only add always if you need always. You now have location always and location when in use you can request manually, else it tries to.figire it out.

**Comment by Hum4nz** [comment] 2017-10-17 15:43
I have added the permission NSLocationAlwaysAndWhenInUseUsageDescription but I have not seen any results

**Bug Information**

Version Number of Plugin:2.1.0
Device Tested On: NONE
Simulator Tested On:Iphone 5s and Iphone 6s ios11
Version of VS: vs 15 14.0.25431 upd 3
Version of Xamarin:Xamarin.Forms 2.3.4.270 (latest stable)
Versions of other things you are using:

Xam.Plugin.Geolocator 4.1.1


**Expected Behavior**

A message appear to allow Location authorization

**Actual Behavior**

No message and infinite loop

**Code snippet**

 var newStatus = await CrossPermissions.Current.RequestPermissionsAsync(permission);
                if (newStatus.ContainsKey(permission) && newStatus[permission] != PermissionStatus.Granted)
                {
                    var title = $"{permission} Permission";
                    var question = $"To use the plugin the {permission} permission is required.";
                    var positive = "Settings";
                    var negative = "Maybe Later";
                    var task = Application.Current?.MainPage?.DisplayAlert(title, question, positive, negative);
                    if (task == null)
                        return false;

**Comment by bhapca** [comment] 2017-10-25 09:14
Found https://stackoverflow.com/a/44424419/4199204 useful.
